StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65B676E8BDA1367B}" {
   Id "PRTC-Capture_Action"
   Target_en_us "Capture"
   Target_fr_fr "Capture"
   Modified 1706457275
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65B676E94E15AB59}" {
   Id "PRTC-Protect_Action"
   Target_en_us "Protect"
   Target_fr_fr "Protège"
   Modified 1706457258
   Author "argeo"
   LastChanged "argeo"
  }
 }
}