StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65B676E8BDA1367B}" {
   Id "PRTC-Capture_Action"
   Target_en_us "Capture"
   Target_fr_fr "Capture"
   Modified 1706457275
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65CB0DB987E80469}" {
   Id "PRTC-EditableEntity_EmergencyResponseCenter_S_Name"
   Target_en_us "Emergency Response Center"
   Modified 1707806253
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2CB2AC6F5BBD6}" {
   Id "PRTC-Group_Civilian_2x"
   Target_en_us "Two Civilians"
   Modified 1707267142
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2CB2A3B24BEB6}" {
   Id "PRTC-Group_Civilian_3x"
   Target_en_us "Three Civilians"
   Modified 1707267151
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE399D4F988F}" {
   Id "PRTC-Group_Rural_2x"
   Target_en_us "Two Rural Civilians"
   Modified 1707264294
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE39DD053386}" {
   Id "PRTC-Group_Rural_3x"
   Target_en_us "Three Rural Civilians"
   Modified 1707264301
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE3E5086C0DB}" {
   Id "PRTC-Group_Urban_2x"
   Target_en_us "Two Urban Civilians"
   Modified 1707267179
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE3E494DD7EF}" {
   Id "PRTC-Group_Urban_3x"
   Target_en_us "Three Urban Civilians"
   Modified 1707264315
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65B676E94E15AB59}" {
   Id "PRTC-Protect_Action"
   Target_en_us "Protect"
   Target_fr_fr "Protège"
   Modified 1706457258
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE38A7B27A84}" {
   Id "PRTC-Random_Businessman_Name"
   Target_en_us "Random Urban Businessman"
   Modified 1707264250
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE389ED4AC82}" {
   Id "PRTC-Random_Guy_Name"
   Target_en_us "Random Urban Guy"
   Modified 1707264261
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE38972DA1E7}" {
   Id "PRTC-Random_Hipster_Name"
   Target_en_us "Random Urban Hipster"
   Modified 1707264276
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE3B7752CBF8}" {
   Id "PRTC-Random_Rural_Name"
   Target_en_us "Random Rural Civilian"
   Modified 1707262594
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE38B0EA8808}" {
   Id "PRTC-Random_Urban_Name"
   Target_en_us "Random Urban Civilian"
   Modified 1707264284
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA469E55E208}" {
   Id "PRTC-WarCrime_Disguised_Title"
   Target_en_us "Disguised As Hostile Faction"
   Modified 1707548880
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA5B7674FE36}" {
   Id "PRTC-WarCrime_HdcKill_Text"
   Target_en_us "You have killed an \"hors de combat\" enemy soldier. This is a war crime, as per Rule 47: \"Attacks against Persons Hors de Combat\"."\
   "See https://ihl-databases.icrc.org"
   Modified 1707551669
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA58554F5A8D}" {
   Id "PRTC-WarCrime_HdcKill_Title"
   Target_en_us "Hors De Combat Enemy Killed"
   Modified 1707542188
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA596E02D3D9}" {
   Id "PRTC-WarCrime_Multiple_Text"
   Target_en_us "You have committed multiple war crimes."\
   "See https://ihl-databases.icrc.org"
   Modified 1707551648
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA5976013AF9}" {
   Id "PRTC-WarCrime_Multiple_Title"
   Target_en_us "Multiple War Crimes"
   Modified 1707536941
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA7BF34FB521}" {
   Id "PRTC-WarCrime_Perfidy_Title"
   Target_en_us "Perfidy"
   Modified 1707551267
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA5B9A772165}" {
   Id "PRTC-WarCrime_ProtectedKill_Text"
   Target_en_us "You have killed a non-combatant. This is a war crime, as per Rule 1: \"The Principle of Distinction between Civilians and Combatants\"."\
   "See https://ihl-databases.icrc.org"
   Modified 1707551683
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA5BA159F0BC}" {
   Id "PRTC-WarCrime_ProtectedKill_Title"
   Target_en_us "Non-Combatant Killed"
   Modified 1707542152
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA466DEE2265}" {
   Id "PRTC-WarCrime_Rule_Nbr"
   Target_en_us "Rule"
   Modified 1707551015
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA59E9D51C4D}" {
   Id "PRTC-WarCrime_Title_Prefix"
   Target_en_us "War Crime: "
   Modified 1707536734
   Author "argeo"
   LastChanged "argeo"
  }
 }
}