StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65B676E8BDA1367B}" {
   Id "PRTC-Action_Capture"
   Target_en_us "Capture"
   Target_fr_fr "Capturer"
   Modified 1710922342
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65B676E94E15AB59}" {
   Id "PRTC-Action_Protect"
   Target_en_us "Protect"
   Target_fr_fr "Protèger"
   Modified 1710919187
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65F683AE031121E9}" {
   Id "PRTC-Action_ProtectGroup"
   Target_en_us "Protect Group"
   Target_fr_fr "Protéger Groupe"
   Modified 1710919200
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65CB0DB987E80469}" {
   Id "PRTC-EditableEntity_EmergencyResponseCenter_S_Name"
   Target_en_us "Emergency Response Center"
   Target_fr_fr "Centre De Réponse D'Urgence"
   Modified 1710920099
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2CB2AC6F5BBD6}" {
   Id "PRTC-Group_Civilian_2x"
   Target_en_us "Two Civilians"
   Target_fr_fr "Deux Civils"
   Modified 1710919349
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2CB2A3B24BEB6}" {
   Id "PRTC-Group_Civilian_3x"
   Target_en_us "Three Civilians"
   Target_fr_fr "Trois Civils"
   Modified 1710919355
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE399D4F988F}" {
   Id "PRTC-Group_Rural_2x"
   Target_en_us "Two Rural Civilians"
   Target_fr_fr "Deux Civils Ruraux"
   Modified 1710919365
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE39DD053386}" {
   Id "PRTC-Group_Rural_3x"
   Target_en_us "Three Rural Civilians"
   Target_fr_fr "Trois Civils Ruraux"
   Modified 1710919369
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE3E5086C0DB}" {
   Id "PRTC-Group_Urban_2x"
   Target_en_us "Two Urban Civilians"
   Target_fr_fr "Deux Civils Urbains"
   Modified 1710919374
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE3E494DD7EF}" {
   Id "PRTC-Group_Urban_3x"
   Target_en_us "Three Urban Civilians"
   Target_fr_fr "Trois Civils Urbains"
   Modified 1710919379
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65EE818992ADDC55}" {
   Id "PRTC-Hint_Build_EmergencyResponseCenter_Text"
   Target_en_us "An emergency response center is a temporary \"civic center\" which is able to take care of displaced civilians (and POW)."\
   ""\
   "When fleeing, civilians will try to reach te nearest civic center, usually a municipal building in a bigger town. By building an emergency response center you can direct them away from the fighting."\
   ""\
   "You can at some point discharge them in the immediate vicinity of a civic center (either a municipal building or an emergency response center)."
   Target_fr_fr "Un centre de réponse d'urgence est un \"centre civique\" temporaire qui peut s'occuper des civils déplacés (et des prisonniers de guerre)."\
   ""\
   "Lorsqu'ils fuient les combats, les civils tenteront de se rendre vers le centre civique le plus proche, généralement un bâtiment municipal dans une ville. En construisant un centre de réponse d'urgence, vous pouvez les diriger loin des combats."\
   ""\
   "Vous pouvez également vous décharger des civils que vous protégez à proximité d'un centre civique (cad. soit un bâtiment municipal, soit un centre de réponse d'urgence)."
   Modified 1710919832
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65EE8189AEE31B8F}" {
   Id "PRTC-Hint_Build_EmergencyResponseCenter_Title"
   Target_en_us "Building An Emergency Response Center"
   Target_fr_fr "Construire Un Centre De Réponse D'Urgence"
   Modified 1710920087
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65EE818AB4AC8050}" {
   Id "PRTC-Hint_Command_Capture_Text"
   Target_en_us "You can capture AI enemies with the command menu, just like you would recruit AI soldiers."\
   ""\
   "When enemies are captured within such a commanded group, they gain a special status and AIs from your own faction won't target them."\
   ""\
   "You can at some point discharge them in the immediate vicinity of a civic center (either a municipal building or an emergency response center)."
   Target_fr_fr "Vous pouvez capturer des IA ennemies avec le menu de commandement, comme vous le feriez pour recruter des soldats IA."\
   ""\
   "Lorsque des ennemis sont capturés dans un tel groupe commandé, ils gagnent un statut spécial et les IAs de votre propre faction ne les viseront pas."\
   ""\
   "Vous pouvez vous en décharger à proximité d'un centre civique (soit un bâtiment municipal soit un centre de réponse d'urgence)."
   Modified 1710919966
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65EE818B493ED0CC}" {
   Id "PRTC-Hint_Command_Capture_Title"
   Target_en_us "Capturing Enemies"
   Target_fr_fr "Capturer Des Ennemis"
   Modified 1710920118
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65CD0DC4C2E79F74}" {
   Id "PRTC-Hint_Command_Protect_Text"
   Target_en_us "You can \"protect\" civilians with the command menu, just like you would recruit AI soldiers."\
   ""\
   "When non-combatants are protected within such a commanded group, they gain a special status and even criminal enemies won't target them."\
   ""\
   "You can at some point discharge them in the immediate vicinity of a civic center (either a municipal building or an emergency response center)."
   Target_fr_fr "Vous pouvez \"protéger\" des civils avec le menu de commandement, comme vous le feriez pour recruter des soldats IA."\
   ""\
   "Lorsque des non-combattants sont protégés dans un tel groupe commandé, ils gagnent un statut spécial et même les soldats de factions criminelles ne les viseront pas."\
   ""\
   "Vous pouvez vous en décharger à proximité d'un centre civique (soit un bâtiment municipal soit un centre de réponse d'urgence)."
   Modified 1710920202
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65CD0DC4D3CFBB31}" {
   Id "PRTC-Hint_Command_Protect_Title"
   Target_en_us "Protecting Non-Combatants"
   Target_fr_fr "Protéger Des Non-Combattants"
   Modified 1710920219
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE38A7B27A84}" {
   Id "PRTC-Random_Businessman_Name"
   Target_en_us "Random Urban Businessman"
   Target_fr_fr "Businessman Urbain Aléatoire"
   Modified 1710920247
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE389ED4AC82}" {
   Id "PRTC-Random_Guy_Name"
   Target_en_us "Random Urban Guy"
   Target_fr_fr "Gars Urbain Aléatoire"
   Modified 1710920265
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE38972DA1E7}" {
   Id "PRTC-Random_Hipster_Name"
   Target_en_us "Random Urban Hipster"
   Target_fr_fr "Hipster Urbain Aléatoire"
   Modified 1710920273
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE3B7752CBF8}" {
   Id "PRTC-Random_Rural_Name"
   Target_en_us "Random Rural Civilian"
   Target_fr_fr "Civil Rural Aléatoire"
   Modified 1710920283
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C2BE38B0EA8808}" {
   Id "PRTC-Random_Urban_Name"
   Target_en_us "Random Urban Civilian"
   Target_fr_fr "Civil Urbain Aléatoire"
   Modified 1710920291
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA469E55E208}" {
   Id "PRTC-WarCrime_Disguised_Title"
   Target_en_us "Disguised As Hostile Faction"
   Target_fr_fr "Déguisé En Faction Ennemie"
   Modified 1710920418
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA5B7674FE36}" {
   Id "PRTC-WarCrime_HdcKill_Text"
   Target_en_us "You have killed an \"hors de combat\" enemy soldier. This is a war crime, as per Rule 47: \"Attacks against Persons Hors de Combat\"."\
   "See https://ihl-databases.icrc.org"
   Target_fr_fr "Vous avez tué un soldat ennemi hors de combat. C'est un crime de guerre, selon la règle 47 : \"Attaques contre les personnes hors de combat\"."\
   "Voir https://ihl-databases.icrc.org"
   Modified 1710920371
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA58554F5A8D}" {
   Id "PRTC-WarCrime_HdcKill_Title"
   Target_en_us "Hors De Combat Enemy Killed"
   Target_fr_fr "Ennemi Hors De Combat Tué"
   Modified 1710920437
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA596E02D3D9}" {
   Id "PRTC-WarCrime_Multiple_Text"
   Target_en_us "You have committed multiple war crimes."\
   "See https://ihl-databases.icrc.org"
   Target_fr_fr "Vous avez commis des crimes de guerre multiples."\
   "Voir https://ihl-databases.icrc.org"
   Modified 1707551648
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA5976013AF9}" {
   Id "PRTC-WarCrime_Multiple_Title"
   Target_en_us "Multiple War Crimes"
   Target_fr_fr "Crimes De Guerre Multiples"
   Modified 1710920458
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA7BF34FB521}" {
   Id "PRTC-WarCrime_Perfidy_Title"
   Target_en_us "Perfidy"
   Target_fr_fr "Perfidie"
   Modified 1707551267
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA5B9A772165}" {
   Id "PRTC-WarCrime_ProtectedKill_Text"
   Target_en_us "You have killed a non-combatant. This is a war crime, as per Rule 1: \"The Principle of Distinction between Civilians and Combatants\"."\
   "See https://ihl-databases.icrc.org"
   Target_fr_fr "Vous avez tué un non-combattant. C'est un crime de guerre, selon la règle 1 : \"Principe de distinction entre les civils et les combattants\"."\
   "Voir https://ihl-databases.icrc.org"
   Modified 1710920475
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA5BA159F0BC}" {
   Id "PRTC-WarCrime_ProtectedKill_Title"
   Target_en_us "Non-Combatant Killed"
   Target_fr_fr "Non-Combattant Tué"
   Modified 1710920486
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA466DEE2265}" {
   Id "PRTC-WarCrime_Rule_Nbr"
   Target_en_us "Rule"
   Target_fr_fr "Règle"
   Modified 1707551015
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65C6EA59E9D51C4D}" {
   Id "PRTC-WarCrime_Title_Prefix"
   Target_en_us "War Crime: "
   Target_fr_fr "Crime de guerre: "
   Modified 1707536734
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65FC745415730D20}" {
   Id "PRTC-XPReward_NonCombatantAbandoned"
   Target_en_us "Non-combatant abandoned"
   Target_fr_fr "Non-combattant abandonné"
   Modified 1711044451
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65FC74546537A2BC}" {
   Id "PRTC-XPReward_NonCombatantDischarged"
   Target_en_us "Non-combatant discharged"
   Target_fr_fr "Déchargé d'un non-combattant"
   Modified 1711044474
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65FC7454D32F686C}" {
   Id "PRTC-XPReward_NonCombatantProtected"
   Target_en_us "Non-combatant protected"
   Target_fr_fr "Non-combattant protégé"
   Modified 1711044495
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65FC7455AB0103AB}" {
   Id "PRTC-XPReward_PrisonerAbandoned"
   Target_en_us "Prisoner abandoned"
   Target_fr_fr "Prisonnier abandonné"
   Modified 1711044505
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65FC74544715270F}" {
   Id "PRTC-XPReward_PrisonerCaptured"
   Target_en_us "Prisoner captured"
   Target_fr_fr "Prisonnier capturé"
   Modified 1711044512
   Author "argeo"
   LastChanged "argeo"
  }
  CustomStringTableItem "{65FC7455904CBE0A}" {
   Id "PRTC-XPReward_PrisonerDischarged"
   Target_en_us "Prisoner discharged"
   Target_fr_fr "Déchargé d'un prisonnier"
   Modified 1711044533
   Author "argeo"
   LastChanged "argeo"
  }
 }
}