SCR_PlaceableEntitiesRegistry {
 m_sAddon "ProtectionCore"
 m_sSourceDirectory "{FD04B5A4ED22E7CC}Prefabs/Characters/Factions/INDFOR/GANG"
 m_bExposed 1
 m_Prefabs {
  "{E062ADE88FDC1A41}Prefabs/Characters/Factions/INDFOR/GANG/Character_GANG_BareChest.et"
 }
}