SCR_PlaceableEntitiesRegistry {
 m_sAddon "ProtectionCore"
 m_sSourceDirectory "{8962DF9139C3EDD6}Prefabs/Characters/Factions/INDFOR/URBAN"
 m_bExposed 1
 m_Prefabs {
  "{036D018C27337044}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Businessman00.et"
  "{E6F14D752BD6E72F}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Businessman01.et"
  "{8AA5799597126801}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Businessman02.et"
  "{5B46A00AC2E7626D}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Guy00.et"
  "{BEDAECF3CE02F506}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Guy01.et"
  "{D28ED81372C67A28}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Guy02.et"
  "{4D12EFF93119C2CE}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Hipster00.et"
  "{A88EA3003DFC55A5}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Hipster01.et"
  "{91B7CCB279B0FC3A}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Guy03.et"
  "{15CC8DA937771163}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Worker00.et"
  "{F050C1503B928608}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Worker01.et"
 }
}