SCR_PlaceableEntitiesRegistry {
 m_sAddon "ProtectionCore"
 m_sSourceDirectory "{8D7E790B87585252}Prefabs/Characters/Factions/INDFOR/RURAL"
 m_bExposed 1
 m_Prefabs {
  "{8541E0C0CDFA6729}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Farmer00.et"
  "{60DDAC39C11FF042}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Farmer01.et"
  "{0C8998D97DDB7F6C}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Farmer02.et"
  "{E915D420713EE807}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Farmer03.et"
  "{D421F11804526130}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Farmer04.et"
  "{31BDBDE108B7F65B}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Farmer05.et"
  "{30FF39F55CD4BC29}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Fisherman01.et"
  "{5460268B4DBF78E3}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Notable01.et"
  "{7D6EE6863B754543}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Worker01.et"
 }
}