SCR_PlaceableEntitiesRegistry {
 m_sAddon "ProtectionCore"
 m_sSourceDirectory "{AFAE2158DE7703AB}Prefabs/Groups/INDFOR/RURAL"
 m_Prefabs {
  "{CD4D00474F1BA890}Prefabs/Groups/INDFOR/RURAL/Group_RURAL_Mix00.et"
 }
}