SCR_PlaceableEntitiesRegistry {
 m_sAddon "ProtectionCore"
 m_sSourceDirectory "{ABB287C260ECBC2F}Prefabs/Groups/INDFOR/URBAN"
 m_Prefabs {
  "{316A6381E4CC77A9}Prefabs/Groups/INDFOR/URBAN/Group_URBAN_Mix00.et"
 }
}