SCR_PlaceableEntitiesRegistry {
 m_sAddon "ProtectionCore"
 m_sSourceDirectory "{FBEAB7592C265E1C}Prefabs/Groups/INDFOR/GANG"
 m_bExposed 1
 m_Prefabs {
  "{9EB0377EE756B199}Prefabs/Groups/INDFOR/GANG/Group_GANG_Mix00.et"
 }
}