SCR_PlaceableEntitiesRegistry {
 m_sAddon "ProtectionCore"
 m_sSourceDirectory "{FBEAB7592C265E1C}Prefabs/Groups/INDFOR/GANG"
 m_bExposed 1
 m_Prefabs {
  "{B3FB23B2257C8D85}Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_covered_GANG_Randomized.et"
 }
}