SCR_NTName {
 m_sWidgetName "PlayerName"
 m_aEntityStates {
  SCR_NTStateText "{69A0DC74930384B2}" {
   m_eEntityState DEFAULT
   m_fOpacityDefault 0
  }
  SCR_NTStateText "{69A0DC74AD37E8C8}" {
   m_eEntityState HIDDEN
   m_fOpacityDefault 0
  }
  SCR_NTStateText "{69A0DC630E613A1F}" {
   m_eEntityState GROUP_MEMBER
   m_vColor 0.259 0.686 0.365 1
   m_fOpacityDefault 0
  }
  SCR_NTStateText "{69A0DC7D6CD52812}" {
   m_eEntityState AI_SUBORDINATE
   m_vColor 0.259 0.686 0.365 1
   m_fOpacityDefault 0
  }
  SCR_NTStateText "{69A0DC7E0EDD304E}" {
   m_eEntityState GROUP_LEADER
   m_vColor 0.259 0.686 0.365 1
   m_fOpacityDefault 0
   m_fShadowOpacity 0
  }
 }
 m_FontResource "{EABA4FE9D014CCEF}UI/Fonts/RobotoCondensed/RobotoCondensed_Bold.fnt"
}