SCR_NTIconBase {
 m_sWidgetName "IconShadowNT"
 m_aEntityStates {
  SCR_NTStateIcon "{69A0DC766C9AA2AB}" {
   m_eEntityState UNCONSCIOUS
   m_fOpacityDefault 0
   m_sImagesetQuad "unconscious-shadow"
  }
  SCR_NTStateIcon "{69A0DC7FC1CD0443}" {
   m_eEntityState GROUP_MEMBER
   m_vColor 0.259 0.686 0.365 1
   m_fOpacityDefault 0.5
   m_sImagesetQuad "pointer-small-shadow"
  }
  SCR_NTStateIcon "{69A0DC7E978E6E38}" {
   m_eEntityState AI_SUBORDINATE
   m_vColor 0.259 0.686 0.365 1
   m_fOpacityDefault 0.5
   m_sImagesetQuad "ai-shadow"
  }
  SCR_NTStateIcon "{69A0DC7FD8CB00B1}" {
   m_eEntityState GROUP_LEADER
   m_vColor 0.624 0.506 0.157 1
   m_fOpacityDefault 0.5
   m_sImagesetQuad "AR_SquadLeader-shadow"
  }
 }
}