SCR_NTIconBase {
 m_sWidgetName "IconNT"
 m_aEntityStates {
  SCR_NTStateIcon "{69A0DC764709667A}" {
   m_eEntityState UNCONSCIOUS
   m_fOpacityDefault 0
   m_sImagesetQuad "unconscious"
  }
  SCR_NTStateIcon "{69A0DC7E12EDAB2C}" {
   m_eEntityState GROUP_MEMBER
   m_vColor 0.259 0.686 0.365 1
   m_sImagesetQuad "pointer-small"
  }
  SCR_NTStateIcon "{69A0DC7D5BEAD28D}" {
   m_eEntityState AI_SUBORDINATE
   m_vColor 0.259 0.686 0.365 1
   m_sImagesetQuad "ai"
  }
  SCR_NTStateIcon "{69A0DC7E16F12B33}" {
   m_eEntityState GROUP_LEADER
   m_vColor 0.624 0.506 0.157 1
   m_sImagesetQuad "AR_SquadLeader"
  }
 }
}