SCR_NameTagConfig {
 m_aSourceEntities SCR_NameTagCollectorBase "{69A0DC6806A94CD1}" {
 }
 m_aVisibilityRuleset SCR_NameTagRulesetFriendlies "{69A0DC6806A94C1F}" {
 }
 m_aZones {
  SCR_NameTagZone "{69A0DC6806A94C1D}" {
   m_sZoneName "Near"
   m_iZoneEnd 15
   m_aElements {
    SCR_NTName "{5D9887870EE2CBFF}" : "{31E8995C44FB2CF2}Configs/NameTags/NameTagPlayerNameElement_Protection.conf" {
     m_aEntityStates {
      SCR_NTStateText "{69A0DC630E613A1F}" {
       m_fOpacityDefault 1
      }
      SCR_NTStateText "{69A0DC7D6CD52812}" {
       m_fOpacityDefault 1
      }
      SCR_NTStateText "{69A0DC7E0EDD304E}" {
       m_fOpacityDefault 1
      }
     }
    }
    SCR_NTIconBase "{5D988780FD72C0CE}" : "{D3298BDD801FB921}Configs/NameTags/NameTagIconElement_Protection.conf" {
     m_aEntityStates {
      SCR_NTStateIcon "{69A0DC764709667A}" {
       m_fOpacityDefault 1
      }
     }
    }
    SCR_NTIconBase "{5D9CD06C8E74938D}" : "{B1276DD56A0767EF}Configs/NameTags/NameTagIconShadowElement_Protection.conf" {
     m_aEntityStates {
      SCR_NTStateIcon "{69A0DC766C9AA2AB}" {
       m_fOpacityDefault 0.5
      }
     }
    }
    SCR_NTIconPlatform "{69A0DC6806A94C6C}" {
     m_sWidgetName "IconNTPlatform"
     m_sImageset "{3262679C50EF4F01}UI/Textures/Icons/icons_wrapperUI.imageset"
    }
    SCR_NTIconPlatform "{69A0DC6806A94C6B}" {
     m_sWidgetName "IconShadowPlatform"
     m_sImageset "{00FE3DBDFD15227B}UI/Textures/Icons/icons_wrapperUI-glow.imageset"
    }
   }
  }
  SCR_NameTagZone "{69A0DC6806A94C73}" {
   m_sZoneName "Far"
   m_iZoneStart 15
   m_iZoneEnd 70
   m_aElements {
    SCR_NTName "{5D9887870EE2CBFF}" : "{31E8995C44FB2CF2}Configs/NameTags/NameTagPlayerNameElement_Protection.conf" {
    }
    SCR_NTIconBase "{5D988780FD72C0CE}" : "{D3298BDD801FB921}Configs/NameTags/NameTagIconElement_Protection.conf" {
    }
    SCR_NTIconBase "{5D9CD06C8E74938D}" : "{B1276DD56A0767EF}Configs/NameTags/NameTagIconShadowElement_Protection.conf" {
    }
    SCR_NTIconPlatform "{69A0DC6806A93E68}" {
     m_sWidgetName "IconNTPlatform"
     m_sImageset "{3262679C50EF4F01}UI/Textures/Icons/icons_wrapperUI.imageset"
    }
    SCR_NTIconPlatform "{69A0DC6806A91C30}" {
     m_sWidgetName "IconShadowPlatform"
     m_sImageset "{00FE3DBDFD15227B}UI/Textures/Icons/icons_wrapperUI-glow.imageset"
    }
   }
  }
  SCR_NameTagZone "{69A0DC6806A91C2B}" {
   m_sZoneName "Scoped"
   m_iZoneStart 0
   m_iZoneEnd 300
   m_aElements {
    SCR_NTName "{5D9887870EE2CBFF}" : "{31E8995C44FB2CF2}Configs/NameTags/NameTagPlayerNameElement_Protection.conf" {
    }
    SCR_NTIconBase "{5D988780FD72C0CE}" : "{D3298BDD801FB921}Configs/NameTags/NameTagIconElement_Protection.conf" {
    }
    SCR_NTIconBase "{5D9CD06C8E74938D}" : "{B1276DD56A0767EF}Configs/NameTags/NameTagIconShadowElement_Protection.conf" {
    }
    SCR_NTIconPlatform "{69A0DC6806A876A6}" {
     m_sWidgetName "IconNTPlatform"
     m_sImageset "{3262679C50EF4F01}UI/Textures/Icons/icons_wrapperUI.imageset"
    }
    SCR_NTIconPlatform "{69A0DC6806A876A7}" {
     m_sWidgetName "IconShadowPlatform"
     m_sImageset "{00FE3DBDFD15227B}UI/Textures/Icons/icons_wrapperUI-glow.imageset"
    }
   }
  }
 }
}