SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{65BD2C0CA1E059F7}" {
   m_sEntityPrefab "{74DF5613F8551847}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Randomized.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{65BD2C0C95DD5ECC}" {
    }
   }
  }
 }
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{65C2F82CF7FC44CD}" {
   m_sIdentifier "Campaign"
   m_aEntities {
    SCR_EntityCatalogEntry "{64DD123A83CD9D0F}" {
     m_sEntityPrefab "{5D35E3203104D858}Prefabs/Characters/Campaign/Final/Campaign_RURAL_Player.et"
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{64DD123B672A3989}" {
       m_eSlotTypes GROUP_SMALL
      }
      SCR_EntityCatalogLoadoutData "{64DD123B742555E3}" {
       m_fSpawnSupplyCost 20
      }
     }
    }
   }
  }
 }
}