SCR_EntityCatalog {
 m_eEntityCatalogType GROUP
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{60EF128FE3A12072}" {
   m_sEntityPrefab "{2E1785FE7C28537D}Prefabs/Groups/INDFOR/RURAL/Group_RURAL_2x.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{65BD2C0F94D26556}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{65BD2C0F8A362D3E}" {
   m_sEntityPrefab "{591DED76888ABC0D}Prefabs/Groups/INDFOR/RURAL/Group_RURAL_3x.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{65BD2C0FFE6657AF}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{64A30CC4421A57AD}" {
   m_sEntityPrefab "{65662525339A7073}Prefabs/Groups/INDFOR/RURAL/Group_RURAL_Population.et"
   m_aEntityDataList {
    SCR_EntityCatalogAmbientPatrolData "{64A30CC4E2977DDD}" {
     m_eGroupType POPULATION
    }
   }
  }
 }
}