SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{60E14906151122BB}" {
   m_sEntityPrefab "{8541E0C0CDFA6729}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Farmer00.et"
  }
  SCR_EntityCatalogEntry "{60E27408DD3E2425}" {
   m_sEntityPrefab "{60DDAC39C11FF042}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Farmer01.et"
  }
  SCR_EntityCatalogEntry "{60E2E12827802BEF}" {
   m_sEntityPrefab "{0C8998D97DDB7F6C}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Farmer02.et"
  }
  SCR_EntityCatalogEntry "{60E2E12833190202}" {
   m_sEntityPrefab "{E915D420713EE807}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Farmer03.et"
  }
  SCR_EntityCatalogEntry "{60E2E12838E4F046}" {
   m_sEntityPrefab "{D421F11804526130}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Farmer04.et"
  }
  SCR_EntityCatalogEntry "{60E2E128AB9A3ADA}" {
   m_sEntityPrefab "{31BDBDE108B7F65B}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Farmer05.et"
  }
 }
}