SCR_EntityCatalog {
 m_eEntityCatalogType GROUP
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{60EF128FE3A12072}" {
   m_sEntityPrefab "{CD4D00474F1BA890}Prefabs/Groups/INDFOR/RURAL/Group_RURAL_Mix00.et"
  }
  SCR_EntityCatalogEntry "{64A30CC4421A57AD}" {
   m_sEntityPrefab "{65662525339A7073}Prefabs/Groups/INDFOR/RURAL/Group_RURAL_Population.et"
   m_aEntityDataList {
    SCR_EntityCatalogAmbientPatrolData "{64A30CC4E2977DDD}" {
     m_eGroupType POPULATION
    }
   }
  }
 }
}