SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{65BD2C0CA1E059F7}" {
   m_sEntityPrefab "{74DF5613F8551847}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Randomized.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{65BD2C0C95DD5ECC}" {
    }
   }
  }
 }
}