SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{60E14906151122BB}" {
   m_sEntityPrefab "{8541E0C0CDFA6729}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Farmer00.et"
  }
  SCR_EntityCatalogEntry "{60E27408DD3E2425}" {
   m_sEntityPrefab "{60DDAC39C11FF042}Prefabs/Characters/Factions/INDFOR/RURAL/Character_RURAL_Farmer01.et"
  }
 }
}