SCR_EntityCatalogMultiList {
 m_eEntityCatalogType GROUP
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{64970901B77E142A}" {
   m_sEntityPrefab "{75A085EFFA4C82F7}Prefabs/Groups/OPFOR/REDPEACE/Group_REDPEACE_Patrol.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{64970901B77E1423}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{64970901B77E1427}" {
     m_eSlotTypes 7
    }
   }
  }
 }
}