SCR_EntityCatalogMultiList {
 m_eEntityCatalogType VEHICLE
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{64E110967C0D56A2}" {
   m_sIdentifier "Vehicles"
   m_aEntities {
    SCR_EntityCatalogEntry "{64E110964688D24F}" {
     m_sEntityPrefab "{6E540072DD8B3B51}Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_PKM_REDPEACE.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{64E11096524B4335}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerOverrideData "{65C311CF433EAB3D}" {
       m_eSlotTypes VEHICLE_MEDIUM
       m_eMinimumRequiredRankOverride PRIVATE
      }
     }
    }
    SCR_EntityCatalogEntry "{64E12087C6DF8248}" {
     m_sEntityPrefab "{13914E94D3B0D844}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_armed_REDPEACE.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{64E12087CF3C70A9}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{64E12087D15AF560}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
   }
  }
 }
}