SCR_EntityCatalog {
 m_eEntityCatalogType WEAPONS_TRIPOD
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{649709027972B0EE}" {
   m_sEntityPrefab "{723870DBB19D30B0}Prefabs/Weapons/Tripods/Tripod_6T5_PKM.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{649709027972B0E8}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{649709027972B0E1}" {
   m_sEntityPrefab "{29F0CC704A582154}Prefabs/Weapons/Tripods/6T7/Tripod_6T7_NSV.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{649709027972B0E0}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{649709027972B0DD}" {
   m_sEntityPrefab "{3EA26CFD7A202636}Prefabs/Weapons/Tripods/6T7/Tripod_6T7_NSV_SPP.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{649709027972B0DC}" {
    }
   }
  }
 }
}