SCR_EntityCatalog {
 m_eEntityCatalogType GROUP
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{60EED3DF62B226F7}" {
   m_sEntityPrefab "{9437AA19314B81AB}Prefabs/Groups/INDFOR/URBAN/Group_URBAN_2x.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{65BD2C0F702FB0D4}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{65BD2C0F78F73B11}" {
   m_sEntityPrefab "{E33DC291C5E96EDB}Prefabs/Groups/INDFOR/URBAN/Group_URBAN_3x.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{65BD2C0F6D518425}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{64A30CC3EC7208E4}" {
   m_sEntityPrefab "{FDB9DA4B64379AEA}Prefabs/Groups/INDFOR/URBAN/Group_URBAN_Population.et"
   m_aEntityDataList {
    SCR_EntityCatalogAmbientPatrolData "{64A30CCDDE1DC5FA}" {
     m_eGroupType POPULATION
    }
   }
  }
 }
}