SCR_EntityCatalog {
 m_eEntityCatalogType GROUP
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{60EED3DF62B226F7}" {
   m_sEntityPrefab "{316A6381E4CC77A9}Prefabs/Groups/INDFOR/URBAN/Group_URBAN_Mix00.et"
  }
 }
}