SCR_EntityCatalog {
 m_eEntityCatalogType GROUP
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{60EED3DF62B226F7}" {
   m_sEntityPrefab "{316A6381E4CC77A9}Prefabs/Groups/INDFOR/URBAN/Group_URBAN_Mix00.et"
  }
  SCR_EntityCatalogEntry "{64A30CC3EC7208E4}" {
   m_sEntityPrefab "{FDB9DA4B64379AEA}Prefabs/Groups/INDFOR/URBAN/Group_URBAN_Population.et"
   m_aEntityDataList {
    SCR_EntityCatalogAmbientPatrolData "{64A30CCDDE1DC5FA}" {
     m_eGroupType POPULATION
    }
   }
  }
 }
}