SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{60E27408E2713B4D}" {
   m_sEntityPrefab "{036D018C27337044}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Businessman00.et"
   m_aEntityDataList {
    SCR_EntityCatalogSpawnerData "{60EB0C8C1B94D5BB}" {
     m_eSlotTypes GROUP_SMALL
    }
    SCR_EntityCatalogEditorData "{60EB0DF21B65A58B}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{60E27408FE3DB22F}" {
   m_sEntityPrefab "{E6F14D752BD6E72F}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Businessman01.et"
  }
  SCR_EntityCatalogEntry "{60E27408CAD27168}" {
   m_sEntityPrefab "{8AA5799597126801}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Businessman02.et"
  }
  SCR_EntityCatalogEntry "{60E284A392EC2101}" {
   m_sEntityPrefab "{5B46A00AC2E7626D}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Guy00.et"
  }
  SCR_EntityCatalogEntry "{60E284A39ED55AAC}" {
   m_sEntityPrefab "{BEDAECF3CE02F506}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Guy01.et"
  }
  SCR_EntityCatalogEntry "{60E284AC6C5AF9C7}" {
   m_sEntityPrefab "{D28ED81372C67A28}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Guy02.et"
  }
  SCR_EntityCatalogEntry "{60EEBA8DB9749297}" {
   m_sEntityPrefab "{91B7CCB279B0FC3A}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Guy03.et"
  }
  SCR_EntityCatalogEntry "{60E284AC7AFD895B}" {
   m_sEntityPrefab "{4D12EFF93119C2CE}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Hipster00.et"
  }
  SCR_EntityCatalogEntry "{60E284AC4128873E}" {
   m_sEntityPrefab "{A88EA3003DFC55A5}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Hipster01.et"
  }
  SCR_EntityCatalogEntry "{60EEBA8D84C4BE23}" {
   m_sEntityPrefab "{15CC8DA937771163}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Worker00.et"
  }
  SCR_EntityCatalogEntry "{60EEBA8D923B127F}" {
   m_sEntityPrefab "{F050C1503B928608}Prefabs/Characters/Factions/INDFOR/URBAN/Character_URBAN_Worker01.et"
  }
 }
}