FactionIdentity {
 VisualIdentityArray {
  VisualIdentity "{570CE64C790A3C7D}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   Head "{04F4D8CBA36A534B}Prefabs/Characters/Heads/Head_Black_02.et"
   Body "{6253161EEAB88EAB}Prefabs/Characters/Basebody/CharacterBasebody_Black_02.et"
  }
 }
 SoundIdentityArray {
  SoundIdentity "{649709037BF7362E}" {
   VoiceID 1
   VoicePitch 0
  }
  SoundIdentity "{649709037BF73628}" {
   VoiceID 1
   VoicePitch 1
  }
  SoundIdentity "{649709037BF73626}" {
   VoiceID 1
   VoicePitch -0.9
  }
  SoundIdentity "{649709037BF73625}" {
   VoiceID 2
   VoicePitch 0
  }
  SoundIdentity "{649709037BF73624}" {
   VoiceID 2
   VoicePitch 0.9
  }
  SoundIdentity "{649709037BF73622}" {
   VoiceID 2
   VoicePitch -0.9
  }
 }
 SocialIdentity SocialIdentity "{649709037BF73621}" {
  NamesConfig {
   "#AR-FirstName_EN_Adam"
   "#AR-FirstName_EN_Brian"
   "#AR-FirstName_EN_Charlie"
   "#AR-FirstName_EN_Christopher"
   "#AR-FirstName_EN_Daniel"
   "#AR-FirstName_EN_David"
   "#AR-FirstName_EN_Edward"
   "#AR-FirstName_EN_James"
   "#AR-FirstName_EN_Jerry"
   "#AR-FirstName_EN_John"
   "#AR-FirstName_EN_Joseph"
   "#AR-FirstName_EN_Luke"
   "#AR-FirstName_EN_Mark"
   "#AR-FirstName_EN_Michael"
   "#AR-FirstName_EN_Patrick"
   "#AR-FirstName_EN_Paul"
   "#AR-FirstName_EN_Peter"
   "#AR-FirstName_EN_Richard"
   "#AR-FirstName_EN_Scott"
   "#AR-FirstName_EN_Steven"
   "#AR-FirstName_EN_Ted"
   "#AR-FirstName_EN_Thomas"
   "#AR-FirstName_EN_William"
  }
  SurnamesConfig {
   "#AR-Surname_EN_Anderson"
   "#AR-Surname_EN_Allen"
   "#AR-Surname_EN_Baker"
   "#AR-Surname_EN_Brown"
   "#AR-Surname_EN_Clark"
   "#AR-Surname_EN_Collins"
   "#AR-Surname_EN_Davis"
   "#AR-Surname_EN_Harris"
   "#AR-Surname_EN_Jackson"
   "#AR-Surname_EN_Jones"
   "#AR-Surname_EN_Johnson"
   "#AR-Surname_EN_King"
   "#AR-Surname_EN_Lee"
   "#AR-Surname_EN_Lewis"
   "#AR-Surname_EN_Martin"
   "#AR-Surname_EN_Miller"
   "#AR-Surname_EN_Reed"
   "#AR-Surname_EN_Ryan"
   "#AR-Surname_EN_Smith"
   "#AR-Surname_EN_Taylor"
   "#AR-Surname_EN_Turner"
   "#AR-Surname_EN_Williams"
   "#AR-Surname_EN_Wilson"
  }
 }
}