EditablePrefabsComponent_EditableEntity : "{0B20C81420906165}Configs/Workbench/EditablePrefabs/EditablePrefabsComponent_EditableEntity.conf" {
 m_EntityLabelRules {
  EditablePrefabsLabel_Faction "{60EB0A5686C69CD0}" {
   m_Label FACTION_RURAL
   m_FactionToCheck "RURAL"
  }
  EditablePrefabsLabel_Faction "{60EB0A569545E8CF}" {
   m_Label FACTION_URBAN
   m_FactionToCheck "URBAN"
  }
 }
}