EditablePrefabsConfig {
 m_sSourceBlacklist "_base,_Base,_dst,_Dst,_DST,_Population"
 m_Settings {
  EditablePrefabsSetting "{525E861ED08E703D}" {
   m_Components {
    EditablePrefabsComponent_EditableEntity "{52827C18A3D91B2D}" {
     m_sLocKeyFormat "#PRTC-EditableEntity_%1_Name"
    }
   }
  }
  EditablePrefabsSetting "{54D89DB338E9F61A}" {
   m_Components {
    EditablePrefabsComponent_EditableEntity "{54B29D2F55007DBD}" {
     m_sLocKeyFormat "#PRTC-EditableEntity_%1_Name"
     m_ImagePlaceholder "{E0E7B854470821EC}UI/Textures/EditorPreviews/System/editorPreviewTemplate.edds"
    }
   }
  }
 }
}