SCR_PlaceableEntitiesRegistry {
 m_sAddon "ProtectionCore"
 m_sSourceDirectory "{79DD690A0F239399}Prefabs/Systems"
 m_Prefabs {
  "{411391AB66DD182B}PrefabsEditable/Auto/Systems/Arsenal/ArsenalBoxes/RURAL/E_ArsenalBox_RURAL.et"
  "{30EFC74659A053DF}PrefabsEditable/Auto/Systems/Arsenal/ArsenalBoxes/URBAN/E_ArsenalBox_URBAN.et"
 }
}