SCR_PlaceableEntitiesRegistry {
 m_sAddon "ProtectionCore"
 m_sSourceDirectory "{79DD690A0F239399}Prefabs/Systems"
 m_Prefabs {
  "{4E7A1E0BFD1E5F47}PrefabsEditable/SpawnPoints/E_SpawnPoint_GANG.et"
  "{A81F31C694165D8D}PrefabsEditable/Auto/Systems/Arsenal/ArsenalBoxes/GANG/E_ArsenalBox_GANG.et"
 }
}