SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{65C2CB2BF8B427C3}" {
   m_sEntityPrefab "{FE04EF539D38553E}Prefabs/Groups/CIV/Group_CIV_2x.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{65C2CB2BF2771553}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{65C2CB2BE50D1711}" {
   m_sEntityPrefab "{890E87DB699ABA4E}Prefabs/Groups/CIV/Group_CIV_3x.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{65C2CB2BDCACD69C}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{64AF0C80836773BE}" {
   m_sEntityPrefab "{53105B088649240C}Prefabs/Groups/CIV/Group_CIV_Population.et"
   m_aEntityDataList {
    SCR_EntityCatalogAmbientPatrolData "{64AF0C81602EB96F}" {
     m_eGroupType POPULATION
    }
   }
  }
 }
}