SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{64AF0C80836773BE}" {
   m_sEntityPrefab "{FF333A7C2BE71BD3}Prefabs/Groups/CIV/Group_CIV_Population.et"
   m_aEntityDataList {
    SCR_EntityCatalogAmbientPatrolData "{64AF0C81602EB96F}" {
     m_eGroupType POPULATION
    }
   }
  }
 }
}