SCR_PlayerCommandingMenuActionsSetup {
 m_aActionConfigPairs {
  SCR_PlayerCommandingConfigActionPair "{610AD9166D01DD2B}" {
   m_sCommandingMenuConf "{737A87F18959FF5F}Configs/Commanding/ProtectionCommandingMenu.conf"
  }
 }
}