SCR_PlayerCommandsConfig {
 m_aCommands {
  ARGEO_RecruitAIGroupCommand "{5A16938165F68ACE}" {
  }
  ARGEO_RemoveAIGroupCommand "{5A16938165F68ACB}" {
  }
  ARGEO_ProtectionFollowGroupCommand "{5A16938165F68AD5}" {
  }
  ARGEO_ProtectAIGroupCommand "{64A90CD955AF2CCF}" {
   m_sCommandName "protectAI"
   m_sCommandDisplayName "#PRTC-Protect_Action"
   m_sImageset "{A4A692135635424E}UI/Imagesets/Commanding/Commanding_Icons.imageset"
   m_sIconName "recruit"
   m_iGestureID 1
   m_sSoundEventName "SOUND_REPORTS_RECRUIT"
  }
  ARGEO_ProtectAIGroupCommand "{64A914092027153F}" {
   m_sCommandName "protectAIGroup"
   m_sCommandDisplayName "Protect Group"
   m_sIconName "squad"
   m_iGestureID 1
   m_sSoundEventName "SOUND_REPORTS_RECRUIT"
   m_bApplyToGroup 1
  }
  ARGEO_CaptureAIGroupCommand "{658AE61153594E37}" {
   m_sCommandName "capture"
   m_sCommandDisplayName "#PRTC-Capture_Action"
   m_sImageset "{A4A692135635424E}UI/Imagesets/Commanding/Commanding_Icons.imageset"
   m_sIconName "recruit"
   m_bShowToMember 1
  }
 }
}