SCR_PlayerCommandingMenuActionsSetup {
 m_aActionConfigPairs {
  SCR_PlayerCommandingConfigActionPair "{64AD31E0413E517C}" {
   m_sActionName "OpenCommandMenu"
   m_sCommandingMenuConf "{737A87F18959FF5F}Configs/Commanding/ProtectionCommandingMenu.conf"
  }
  SCR_PlayerCommandingConfigActionPair "{64AD31E0413E5168}" {
   m_sActionName "OpenEmoteMenu"
   m_sCommandingMenuConf "{21EF57F81572C967}Configs/Commanding/EmoteMenu.conf"
  }
 }
}