SCR_PlayerCommandingMenuConfig {
 m_RootCategory SCR_PlayerCommandingMenuCategoryElement "{64AD31E006FEEBED}" {
  m_sCategoryDisplayText "#AR-Commanding_Commanding"
  m_aElements {
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBE5}" {
    m_sCommandName "recruitAI"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E01B2B38B1}" {
    m_sCommandName "protectAI"
   }
   SCR_PlayerCommandingMenuCommand "{658AE612989ABB78}" {
    m_sCommandName "capture"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBE0}" {
    m_sCommandName "removeAI"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBDE}" {
    m_sCommandName "follow"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBDF}" {
    m_sCommandName "waypointMoveForced"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBDC}" {
    m_sCommandName "waypointMountNear"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBDD}" {
    m_sCommandName "waypointDefend"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBDA}" {
    m_sCommandName "halt"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBDB}" {
    m_sCommandName "getOutVehicle"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBD8}" {
    m_sCommandName "waypointSuppress"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBD9}" {
    m_sCommandName "contextGetInCommand"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBD6}" {
    m_sCommandName "characterEntityHealCommand"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBD7}" {
    m_sCommandName "lookAtCommand"
   }
  }
 }
}