SCR_PlayerCommandsConfig : "{54764D4E706F348C}Configs/Commanding/Commands.conf" {
 m_aCommands {
  SCR_RecruitAIGroupCommand "{5A16938165F68ACE}" {
  }
  ARGEO_ProtectAIGroupCommand "{64750727037E2219}" {
   m_sCommandName "protectAI"
   m_sCommandDisplayName "Protect"
   m_sIconName "lawsOfWar"
   m_bShowToMember 1
   m_iGestureID 1
   m_sSoundEventName "SOUND_REPORTS_RECRUIT"
  }
 }
}