SCR_PlayerCommandingMenuConfig : "{ECC45EC468D76CF5}Configs/Commanding/CommandingMenu.conf" {
 m_RootCategory SCR_PlayerCommandingMenuCategoryElement "{5A4ED511170B5C06}" {
  m_aElements {
   SCR_PlayerCommandingMenuCommand "{64750724F793E44B}" {
    m_sCommandName "protectAI"
    m_sCommandDisplayText "Protect"
   }
   SCR_PlayerCommandingMenuCategoryElement "{64A8F39BBA82689B}" {
    m_sCategoryDisplayText "Protection"
    m_aElements {
     SCR_PlayerCommandingMenuCommand "{64A8F39B966A4EDE}" {
      m_sCommandName "protectAIGroup"
      m_sCommandDisplayText "Protect Group"
     }
    }
   }
  }
 }
}