SCR_PlayerCommandingMenuConfig : "{737A87F18959FF5F}Configs/Commanding/ProtectionCommandingMenu.conf" {
 m_RootCategory SCR_PlayerCommandingMenuCategoryElement "{64AD31E006FEEBED}" {
  m_aElements {
   SCR_PlayerCommandingMenuCategoryElement "{64AD31E42C28E8B8}" {
    m_sCategoryDisplayText "Protection Commands"
    m_aElements {
     SCR_PlayerCommandingMenuCommand "{64AD31E0D3580099}" {
      m_sCommandName "protectAIGroup"
      m_sCommandDisplayText "Protect Group"
     }
    }
   }
  }
 }
}