SCR_PlayerCommandingMenuConfig {
 m_RootCategory SCR_PlayerCommandingMenuCategoryElement "{64AD31E7E86F338C}" {
  m_sCategoryDisplayText "#AR-FieldManual_Page_Commanding_Title"
  m_aElements {
   SCR_PlayerCommandingMenuCommand "{64AD31E7E86F3386}" {
    m_sCommandName "waypointMoveForced"
    m_sCommandDisplayText "#AR-Commanding_Command_Move"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E7E86F3385}" {
    m_sCommandName "waypointDefend"
    m_sCommandDisplayText "#AR-Commanding_Command_Defend"
   }
  }
  m_bShowOnMap 1
 }
}