SCR_PlayerCommandingMenuConfig {
 m_RootCategory SCR_PlayerCommandingMenuCategoryElement "{64AD31E006FEEBED}" {
  m_sCategoryDisplayText "#AR-Commanding_Commanding"
  m_aElements {
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBE5}" {
    m_sCommandName "recruitAI"
    m_sCommandDisplayText "#AR-Commanding_Command_Recruit"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E01B2B38B1}" {
    m_sCommandName "protectAI"
    m_sCommandDisplayText "Protect"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBE0}" {
    m_sCommandName "removeAI"
    m_sCommandDisplayText "#AR-Commanding_Command_Kick"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBDE}" {
    m_sCommandName "follow"
    m_sCommandDisplayText "#AR-Commanding_Command_Follow"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBDF}" {
    m_sCommandName "waypointMoveForced"
    m_sCommandDisplayText "#AR-Commanding_Command_Move"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBDC}" {
    m_sCommandName "waypointMountNear"
    m_sCommandDisplayText "#AR-Commanding_Command_MountNearby"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBDD}" {
    m_sCommandName "waypointDefend"
    m_sCommandDisplayText "#AR-Commanding_Command_Defend"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBDA}" {
    m_sCommandName "halt"
    m_sCommandDisplayText "#AR-Commanding_Command_Halt"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBDB}" {
    m_sCommandName "getOutVehicle"
    m_sCommandDisplayText "#AR-UserAction_GetOut"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBD8}" {
    m_sCommandName "waypointSuppress"
    m_sCommandDisplayText "#AR-Commanding_Command_SuppressFire"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBD9}" {
    m_sCommandName "contextGetInCommand"
    m_sCommandDisplayText "#AR-Editor_CommandAction_AIWaypoint_GetInNearest_Name"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBD6}" {
    m_sCommandName "characterEntityHealCommand"
    m_sCommandDisplayText "#AR-Commanding_Command_Heal"
   }
   SCR_PlayerCommandingMenuCommand "{64AD31E006FEEBD7}" {
    m_sCommandName "lookAtCommand"
    m_sCommandDisplayText "#AR-Commanding_Command_LookAt"
   }
  }
 }
}