SCR_XPRewardList {
 m_aRewardList {
  SCR_XPRewardInfo "{65E306D67E9BA026}" {
   m_eRewardID NON_COMBATANT_KILL
   m_sRewardName "#AR-Campaign_XPReward_Warcrime"
   m_iRewardXP -100
  }
  SCR_XPRewardInfo "{65E306D66D097157}" {
   m_eRewardID HORS_DE_COMBAT_KILL
   m_sRewardName "#AR-Campaign_XPReward_Warcrime"
   m_iRewardXP -50
  }
  SCR_XPRewardInfo "{65E306D614C402BE}" {
   m_eRewardID PERFIDY
   m_sRewardName "#AR-Campaign_XPReward_KillingWhileDisguised"
   m_iRewardXP -50
  }
  SCR_XPRewardInfo "{65E30DDCBB3F6BED}" {
   m_eRewardID PROTECT_NON_COMBATANT
   m_sRewardName "Non-Combatant Protected"
   m_iRewardXP 30
  }
  SCR_XPRewardInfo "{65E30DDB5EE9BB35}" {
   m_eRewardID ABANDON_NON_COMBATANT
   m_sRewardName "Non-Combatant Abandoned"
   m_iRewardXP -30
  }
  SCR_XPRewardInfo "{65E3182B34CB5EF0}" {
   m_eRewardID DISCHARGE_NON_COMBATANT
   m_sRewardName "Non-Combatant Discharged"
   m_iRewardXP 30
  }
  SCR_XPRewardInfo "{65E30DDB76BAE5CA}" {
   m_eRewardID CAPTURE_PRISONER
   m_sRewardName "Prisoner Captured"
   m_iRewardXP 30
  }
  SCR_XPRewardInfo "{65E30DDB65D0BE88}" {
   m_eRewardID ABANDON_PRISONER
   m_sRewardName "Prisoner Abandoned"
   m_iRewardXP -30
  }
  SCR_XPRewardInfo "{65E3182B25717CCE}" {
   m_eRewardID DISCHARGE_PRISONER
   m_sRewardName "Prisoner Discharged"
  }
 }
}