SCR_CampaignBuildingCompositionOutlineManager {
 m_aCompositionLayouts {
  SCR_CampaignBuildingCompositionOutline "{65CB0C2BE01507E0}" {
   m_sEditableEntity "{FF7BB2F4C012B969}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_EmergencyResponseCenter_S_US.et"
   m_sCompositionLayout "{7FD4E6A668B4537A}Prefabs/Compositions/Misc/FreeRoamBuilding/Layouts/FRB_SlotFLatSmall.et"
  }
  SCR_CampaignBuildingCompositionOutline "{65DED1D66772F7F9}" {
   m_sEditableEntity "{1A4947C79F64D9B8}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_EmergencyResponseCenter_S_USSR.et"
   m_sCompositionLayout "{7FD4E6A668B4537A}Prefabs/Compositions/Misc/FreeRoamBuilding/Layouts/FRB_SlotFLatSmall.et"
  }
 }
}