SCR_CampaignBuildingCompositionOutlineManager {
 m_aCompositionLayouts {
  SCR_CampaignBuildingCompositionOutline "{64791B9EFA8DFCCC}" {
   m_sEditableEntity "{18BD3B067D00FF3D}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_LivingArea_S_GANG_01.et"
   m_sCompositionLayout "{0828F87137D2F0C0}Prefabs/Compositions/Misc/FreeRoamBuilding/Layouts/FRB_LivingArea_S_01.et"
  }
  SCR_CampaignBuildingCompositionOutline "{64791B9EDAEC1B1D}" {
   m_sEditableEntity "{A81F1CA0AAE8561E}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_Antenna_S_GANG_01.et"
   m_sCompositionLayout "{7FD4E6A668B4537A}Prefabs/Compositions/Misc/FreeRoamBuilding/Layouts/FRB_SlotFLatSmall.et"
  }
  SCR_CampaignBuildingCompositionOutline "{64791B9EB0C411B9}" {
   m_sEditableEntity "{7CBCBA91D3F27603}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_VehicleMaintenance_S_GANG_01.et"
   m_sCompositionLayout "{B2EAAF9C153CAFDE}Prefabs/Compositions/Misc/FreeRoamBuilding/Layouts/FRB_VehicleMaintenance_S_01.et"
  }
  SCR_CampaignBuildingCompositionOutline "{65CB0C2BE01507E0}" {
   m_sEditableEntity "{FF7BB2F4C012B969}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_EmergencyResponseCenter_S_US.et"
   m_sCompositionLayout "{7FD4E6A668B4537A}Prefabs/Compositions/Misc/FreeRoamBuilding/Layouts/FRB_SlotFLatSmall.et"
  }
  SCR_CampaignBuildingCompositionOutline "{65DED1D66772F7F9}" {
   m_sEditableEntity "{1A4947C79F64D9B8}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_EmergencyResponseCenter_S_USSR.et"
   m_sCompositionLayout "{7FD4E6A668B4537A}Prefabs/Compositions/Misc/FreeRoamBuilding/Layouts/FRB_SlotFLatSmall.et"
  }
 }
}