SCR_Faction : "{3FA20B01D950D31E}Configs/Factions/Non-Combatant.conf" {
 m_FactionHomeTerritoryConfig SCR_FactionHomeTerritoryConfig "{6134C337FF7969DC}" {
  m_aFactionHomeTerritories {
   SCR_FactionHomeTerritory "{65DE790E41895ED1}" {
    m_sID "Erquy"
    m_UIInfo SCR_UIInfo "{65DE790E7161F386}" {
     Name "#AR-MapLocation_Erquy"
    }
    m_iWeight 17
   }
   SCR_FactionHomeTerritory "{65DE790E7CF0F683}" {
    m_sID "Villeneuf"
    m_UIInfo SCR_UIInfo "{65DE790E7CF0F704}" {
     Name "#AR-MapLocation_Villeneuf"
    }
    m_iWeight 15
   }
   SCR_FactionHomeTerritory "{65DE8401A0A45E2B}" {
    m_sID "Lancre"
    m_UIInfo SCR_UIInfo "{65DE8401A0A45E55}" {
     Name "#AR-MapLocation_Lancre"
    }
    m_iWeight 5
   }
   SCR_FactionHomeTerritory "{65DE84064637199D}" {
    m_sID "LesCreux"
    m_UIInfo SCR_UIInfo "{65DE8406463719EE}" {
     Name "#AR-MapLocation_LesCreux"
    }
    m_iWeight 2
   }
   SCR_FactionHomeTerritory "{65DE84067280CC8E}" {
    m_sID "Etoupe"
    m_UIInfo SCR_UIInfo "{65DE84067280CCB6}" {
     Name "#AR-MapLocation_Etoupe"
    }
    m_iWeight 8
   }
   SCR_FactionHomeTerritory "{65DE8406628E8170}" {
    m_sID "Kermovan"
    m_UIInfo SCR_UIInfo "{65DE8406628E81B9}" {
     Name "#AR-MapLocation_Kermovan"
    }
    m_iWeight 8
   }
   SCR_FactionHomeTerritory "{65DE840611FAB81C}" {
    m_sID "Redon"
    m_UIInfo SCR_UIInfo "{65DE840611FAB845}" {
     Name "#AR-MapLocation_Redon"
    }
    m_iWeight 5
   }
  }
  m_bIsFactionPopulation 1
 }
}