SCR_Faction : "{277AE7613D88A55B}Configs/Factions/INDFOR.conf" {
 FactionKey "GANG"
 FactionColor 0 0.44 0.433 1
 UIInfo SCR_FactionUIInfo "{60EB3E6099F04381}" {
  Name "Gang"
  Description "Urban gangstas"
  Icon "{CF4545F580A34FA7}Assets/Props/Fabric/Flags/Data/Flag_1_2_Blue_BCR.edds"
  m_sNameUpper "GANG"
 }
 "Identity of soldiers" FactionIdentity "{60EB3E6177F302E7}" : "{320F453E4F0D9CD8}Configs/Identities/FactionIdentity_URBAN.conf" {
 }
 m_OutlineFactionColor 0 0.44 0.433 1
 m_sFactionFlag "{CF4545F580A34FA7}Assets/Props/Fabric/Flags/Data/Flag_1_2_Blue_BCR.edds"
 m_FactionFlagMaterial "{DB52C2D4463AA0A0}Assets/Props/Fabric/Flags/Data/Flag_2_3_Blue.emat"
 m_FactionLabel FACTION_GANG
 m_aFriendlyFactionsIds {
  "US"
  "URSS"
  "RURAL"
  "URBAN"
  "RHS_RF_MSV"
  "RHS_US_USMC"
 }
 m_CallsignInfo SCR_FactionCallsignInfo "{60EEEB4EBEB581AE}" : "{D7164359D005B37A}Configs/Callsigns/Callsigns_FIA.conf" {
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{60EB3E62FE80A85E}" : "{23E53EBCB994EFD9}Configs/EntityCatalog/GANG/GANG_Characters.conf" {
  }
  SCR_EntityCatalog "{60EED3DF77416CE0}" : "{E37F0AF365F131B1}Configs/EntityCatalog/GANG/GANG_Groups.conf" {
  }
  SCR_EntityCatalogMultiList "{60F0FA283BACAE26}" : "{510544B59DEC03ED}Configs/EntityCatalog/GANG/GANG_InventoryItems.conf" {
  }
 }
}