SCR_Faction : "{277AE7613D88A55B}Configs/Factions/INDFOR.conf" {
 FactionKey "GANG"
 FactionColor 0 0 0 1
 UIInfo SCR_FactionUIInfo "{60EB3E6099F04381}" {
  Name "Gang"
  Description "Urban gangstas"
  Icon "{BD2E2F871E6A3EBF}UI/Textures/Flags/Flag_Faction_Base.edds"
  m_sNameUpper "GANG"
 }
 "Identity of soldiers" FactionIdentity "{60EB3E6177F302E7}" : "{320F453E4F0D9CD8}Configs/Identities/FactionIdentity_URBAN.conf" {
 }
 m_OutlineFactionColor 0 0 0 1
 m_sFactionFlag "{BD2E2F871E6A3EBF}UI/Textures/Flags/Flag_Faction_Base.edds"
 m_FactionFlagMaterial "{4A53EF08996B2AA7}Assets/Props/Fabric/Flags/Data/Flag_2_3_Green.emat"
 m_FactionLabel FACTION_GANG
 m_aFriendlyFactionsIds {
  "US"
  "URSS"
  "FIA"
  "RURAL"
  "URBAN"
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{60EB3E62FE80A85E}" : "{23E53EBCB994EFD9}Configs/EntityCatalog/GANG/GANG_Characters.conf" {
  }
  SCR_EntityCatalog "{60EED3DF77416CE0}" : "{E37F0AF365F131B1}Configs/EntityCatalog/GANG/GANG_Groups.conf" {
  }
 }
}