SCR_CampaignFaction : "{5C630F7CDC94DACA}Configs/Factions/GANG.conf" {
 m_DefendersGroupPrefab "{9EB0377EE756B199}Prefabs/Groups/INDFOR/GANG/Group_GANG_Mix00.et"
 m_RadioPrefab "{9B6B61BB3FE3DFB0}Prefabs/Items/Equipment/Radios/Radio_ANPRC77.et"
 m_BaseBuildingHQ "{7CB2EB208F93C6D4}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_Headquarters_S_FIA_01.et"
}