SCR_Faction : "{277AE7613D88A55B}Configs/Factions/INDFOR.conf" {
 FactionKey "GANG"
 FactionColor 0 0.44 0.433 1
 UIInfo SCR_FactionUIInfo "{60EB3E6099F04381}" {
  Name "Gang"
  Description "Urban gangstas"
  Icon "{CF4545F580A34FA7}Assets/Props/Fabric/Flags/Data/Flag_1_2_Blue_BCR.edds"
  m_sNameUpper "GANG"
 }
 "Identity of soldiers" FactionIdentity "{60EB3E6177F302E7}" : "{320F453E4F0D9CD8}Configs/Identities/FactionIdentity_URBAN.conf" {
 }
 m_OutlineFactionColor 0 0.44 0.433 1
 m_sFactionFlag "{CF4545F580A34FA7}Assets/Props/Fabric/Flags/Data/Flag_1_2_Blue_BCR.edds"
 m_FactionFlagMaterial "{DB52C2D4463AA0A0}Assets/Props/Fabric/Flags/Data/Flag_2_3_Blue.emat"
 m_FactionLabel FACTION_GANG
 m_aFriendlyFactionsIds {
  "CIV"
  "US"
  "USSR"
  "RURAL"
  "URBAN"
 }
 m_CallsignInfo SCR_FactionCallsignInfo "{60EEEB4EBEB581AE}" : "{D7164359D005B37A}Configs/Callsigns/Callsigns_FIA.conf" {
 }
 m_aRanks {
  SCR_CharacterRank "{64791B9BCD1817A1}" {
   m_iRank PRIVATE
   m_sRankName "#AR-Rank_WestPrivate"
   m_sRankNameUpper "#AR-Rank_WestPrivate-UC"
   m_sRankNameShort "#AR-Rank_WestPrivateShort"
   m_sInsignia "AR_Rank_OR-2"
  }
  SCR_CharacterRank "{64791B9A75B5AFA9}" {
   m_iRank CORPORAL
   m_sRankName "#AR-Rank_WestCorporal"
   m_sRankNameUpper "#AR-Rank_WestCorporal-UC"
   m_sRankNameShort "#AR-Rank_WestCorporalShort"
   m_sInsignia "AR_Rank_OR-4_C"
  }
  SCR_CharacterRank "{64791B9A41F7D059}" {
   m_iRank SERGEANT
   m_sRankName "#AR-Rank_WestSergeant"
   m_sRankNameUpper "#AR-Rank_WestSergeant-UC"
   m_sRankNameShort "#AR-Rank_WestSergeantShort"
   m_sInsignia "AR_Rank_OR-5"
  }
  SCR_CharacterRank "{64791B9A4E441286}" {
   m_iRank LIEUTENANT
   m_sRankName "#AR-Rank_WestLieutenant"
   m_sRankNameUpper "#AR-Rank_WestLieutenant-UC"
   m_sRankNameShort "#AR-Rank_WestLieutenantShort"
   m_sInsignia "AR_Rank_OF-1_1st"
  }
  SCR_CharacterRank "{64791B9A5A820257}" {
   m_iRank CAPTAIN
   m_sRankName "#AR-Rank_WestCaptain"
   m_sRankNameUpper "#AR-Rank_WestCaptain-UC"
   m_sRankNameShort "#AR-Rank_WestCaptainShort"
   m_sInsignia "AR_Rank_OF-2"
  }
  SCR_CharacterRank "{64791B9A2393F3F0}" {
   m_iRank MAJOR
   m_sRankName "#AR-Rank_WestMajor"
   m_sRankNameUpper "#AR-Rank_WestMajor-UC"
   m_sRankNameShort "#AR-Rank_WestMajorShort"
   m_sInsignia "AR_Rank_OF-3"
  }
  SCR_CharacterRank "{64791B9A297FF75E}" {
   m_iRank RENEGADE
   m_sRankName "#AR-Rank_Renegade"
   m_sRankNameUpper "#AR-Rank_Renegade-UC"
  }
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{60EB3E62FE80A85E}" : "{23E53EBCB994EFD9}Configs/EntityCatalog/GANG/GANG_Characters.conf" {
  }
  SCR_EntityCatalog "{60EED3DF77416CE0}" : "{E37F0AF365F131B1}Configs/EntityCatalog/GANG/GANG_Groups.conf" {
  }
  SCR_EntityCatalogMultiList "{60F0FA283BACAE26}" : "{510544B59DEC03ED}Configs/EntityCatalog/GANG/GANG_InventoryItems.conf" {
  }
 }
}