SCR_Faction : "{7DB5E431F2E16B5F}Configs/Factions/ProtectedFaction.conf" {
 FactionKey "PROTECTED"
 FactionColor 1 1 1 1
 UIInfo SCR_FactionUIInfo "{64ACF014AE6A835E}" {
  Name "Protected"
  Description "Virtual faction assigned to protected AIs such as non-combatants or prisoners of war."
  Icon "{D91B48761E60082F}UI/Textures/Common/Protection/RedCrystal-icon.edds"
  m_sNameUpper "PROTECTED"
 }
 m_OutlineFactionColor 0.216 0.216 0.216 0
 m_NotificationFactionColor 0.216 0.216 0.216 0
 m_NotificationTextFactionColor 0.216 0.216 0.216 1
 m_FactionLabel FACTION_PROTECTED
 m_aEntityCatalogs {
  SCR_EntityCatalog "{65E11923D1F56A60}" {
   m_eEntityCatalogType CHARACTER
  }
  SCR_EntityCatalog "{65E11923C7655C0F}" {
   m_eEntityCatalogType ITEM
  }
  SCR_EntityCatalog "{658D1A2740EDA249}" {
   m_eEntityCatalogType GROUP
  }
  SCR_EntityCatalog "{65E11923CDE020B3}" {
   m_eEntityCatalogType VEHICLE
  }
  SCR_EntityCatalog "{65E11923F42B68F3}" {
   m_eEntityCatalogType WEAPONS_TRIPOD
  }
 }
}