SCR_Faction : "{7DB5E431F2E16B5F}Configs/Factions/ProtectedFaction.conf" {
 FactionKey "PROTECTED"
 m_FactionLabel FACTION_PROTECTED
 m_aEntityCatalogs {
  SCR_EntityCatalog "{658D1A2740EDA249}" {
   m_eEntityCatalogType ITEM
  }
 }
}