SCR_Faction {
 UIInfo SCR_FactionUIInfo "{64ACF014AE6A835E}" {
  Icon "{A154A4D7278D122B}UI/Textures/Editor/EditableEntities/Factions/EditableEntity_Faction_Non-Combatant.edds"
 }
 m_bIsPlayable 0
 m_bShowInWelcomeScreenIfNonPlayable 0
 m_bIsMilitary 0
 m_sFactionFlag "{5482FF3C7863EB18}UI/Textures/Flags/Non-Combatant-flag-base.edds"
 m_FactionFlagMaterial "{936E6C67A71A9421}Assets/Props/Fabric/Flags/Data/Flag_2_3_White.emat"
 m_FactionLabel FACTION_NONE
 m_CallsignInfo SCR_FactionCallsignInfo "{607A9A9E40D70F6E}" : "{4D4B1F0F0B56B2C9}Configs/Callsigns/Callsigns_Non-Combatant.conf" {
 }
 m_sGroupFlagsImageSet "{D7E06968B5F9FC92}UI/Textures/GroupManagement/FlagIcons/GroupFlagsCivilian.imageset"
 m_sGroupFlagsImageSetOutlines "{824ADD5E7A28B03E}UI/Textures/GroupManagement/FlagIcons/GroupFlagsCivilian-outline.imageset"
 m_aFlagNames {
  "land"
  "helicopter"
  "maintenance"
  "medical"
 }
}