SCR_CampaignFaction : "{B709EDB4147259CD}Configs/Factions/REDPEACE.conf" {
 m_DefendersGroupPrefab "{75A085EFFA4C82F7}Prefabs/Groups/OPFOR/REDPEACE/Group_REDPEACE_Patrol.et"
 m_MobileHQPrefab "{E171C9F443958371}Prefabs/MP/Campaign/Assets/CampaignMobileAssemblyEast.et"
 m_RadioPrefab "{54C68E438DD34265}Prefabs/Items/Equipment/Radios/Radio_R107M.et"
 m_BaseBuildingHQ "{847605BB95F1F066}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_Headquarters_S_USSR_01.et"
}