SCR_CampaignFaction : "{E5B2FC4A0D01E456}Configs/Factions/RURAL.conf" {
 m_DefendersGroupPrefab "{9A23B03EC08610D5}Prefabs/Groups/INDFOR/RURAL/Group_RURAL_Base.et"
 m_BaseBuildingHQ "{7CB2EB208F93C6D4}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_Headquarters_S_FIA_01.et"
 m_BaseBuildingSupplyDepot "{E8B6339148792C0E}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_SupplyCache_S_FIA_01.et"
}