SCR_Faction : "{7DB5E431F2E16B5F}Configs/Factions/ProtectedFaction.conf" {
 FactionKey "RURAL"
 FactionColor 0 0.44 0.225 0.5
 UIInfo SCR_FactionUIInfo "{60E1490409A4E9F5}" {
  Name "Rural civilians"
  Icon "{F29DF4A21175C75D}Assets/Props/Fabric/Flags/Data/Flag_1_2_Everon_BCR.edds"
  m_sNameUpper "RURAL CIVILIANS"
 }
 "Identity of soldiers" FactionIdentity "{60E281795DC2AA97}" : "{46413880217C8196}Configs/Identities/FactionIdentity_FIA.conf" {
 }
 m_iOrder 10000
 m_OutlineFactionColor 0 0.094 0.048 0.5
 m_NotificationFactionColor 0 0.44 0.225 0.5
 m_NotificationTextFactionColor 0 0.226 0.115 0.5
 m_bIsPlayable 0
 m_bShowInWelcomeScreenIfNonPlayable 0
 m_bIsMilitary 0
 m_sFactionFlag "{F29DF4A21175C75D}Assets/Props/Fabric/Flags/Data/Flag_1_2_Everon_BCR.edds"
 m_FactionFlagMaterial "{9BE1341F99D33483}Assets/Props/Fabric/Flags/Data/Flag_1_2_EVERON.emat"
 m_FactionLabel FACTION_RURAL
 m_CallsignInfo SCR_FactionCallsignInfo "{607A9A9E40D70F6E}" : "{4D4B1F0F0B56B2C9}Configs/Callsigns/Callsigns_Non-Combatant.conf" {
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{60E14907CE56D40D}" : "{06B2CBCEFD52BFBA}Configs/EntityCatalog/RURAL/RURAL_Characters.conf" {
  }
  SCR_EntityCatalogMultiList "{60E334C53A82AF61}" : "{7686605EE360203C}Configs/EntityCatalog/RURAL/RURAL_InventoryItems.conf" {
  }
  SCR_EntityCatalog "{60EF128F98208B41}" : "{BF53476C3F1CEDF5}Configs/EntityCatalog/RURAL/RURAL_Groups.conf" {
  }
  SCR_EntityCatalogMultiList "{64A5222DABC29485}" : "{7C53DF3E1349C5B8}Configs/EntityCatalog/CIV/Vehicles_EntityCatalog_CIV.conf" {
  }
  SCR_EntityCatalogMultiList "{64A5222DAE6BCC27}" : "{361D4401A7A7102A}Configs/EntityCatalog/CIV/WeaponTripod_EntityCatalog_CIV.conf" {
  }
 }
 m_aFlagNames {
 }
}