SCR_Faction : "{277AE7613D88A55B}Configs/Factions/INDFOR.conf" {
 FactionKey "RURAL"
 FactionColor 0 0.44 0.078 0.5
 UIInfo SCR_FactionUIInfo "{60E1490409A4E9F5}" {
  Name "Rural civilians"
  Icon "{F29DF4A21175C75D}Assets/Props/Fabric/Flags/Data/Flag_1_2_Everon_BCR.edds"
  m_sNameUpper "RURAL CIVILIANS"
 }
 "Identity of soldiers" FactionIdentity "{60E281795DC2AA97}" : "{D6C722BDFF029E1A}Configs/Identities/FactionIdentity_RURAL.conf" {
 }
 m_OutlineFactionColor 0.001 0.082 0.023 0.5
 m_bIsPlayable 0
 m_sFactionFlag "{F29DF4A21175C75D}Assets/Props/Fabric/Flags/Data/Flag_1_2_Everon_BCR.edds"
 m_FactionFlagMaterial "{9BE1341F99D33483}Assets/Props/Fabric/Flags/Data/Flag_1_2_EVERON.emat"
 m_FactionLabel FACTION_RURAL
 m_aFriendlyFactionsIds {
  "FIA"
  "USSR"
  "US"
  "URBAN"
  "GANG"
  "RHS_RF_MSV"
  "RHS_US_USMC"
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{60E14907CE56D40D}" : "{06B2CBCEFD52BFBA}Configs/EntityCatalog/RURAL/RURAL_Characters.conf" {
  }
  SCR_EntityCatalogMultiList "{60E334C53A82AF61}" : "{7686605EE360203C}Configs/EntityCatalog/RURAL/RURAL_InventoryItems.conf" {
  }
  SCR_EntityCatalog "{60EF128F98208B41}" : "{BF53476C3F1CEDF5}Configs/EntityCatalog/RURAL/RURAL_Groups.conf" {
  }
 }
 m_aFlagNames {
 }
}