SCR_Faction : "{277AE7613D88A55B}Configs/Factions/INDFOR.conf" {
 FactionKey "RURAL"
 FactionColor 0 0.44 0.078 0.5
 UIInfo SCR_FactionUIInfo "{60E1490409A4E9F5}" {
  Name "Rural civilians"
  Icon "{BD2E2F871E6A3EBF}UI/Textures/Flags/Flag_Faction_Base.edds"
  m_sNameUpper "RURAL CIVILIANS"
 }
 "Identity of soldiers" FactionIdentity "{60E281795DC2AA97}" : "{D6C722BDFF029E1A}Configs/Identities/FactionIdentity_RURAL.conf" {
 }
 m_OutlineFactionColor 0.001 0.082 0.023 0.5
 m_sFactionFlag "{BD2E2F871E6A3EBF}UI/Textures/Flags/Flag_Faction_Base.edds"
 m_FactionFlagMaterial "{936E6C67A71A9421}Assets/Props/Fabric/Flags/Data/Flag_2_3_White.emat"
 m_FactionLabel FACTION_RURAL
 m_aFriendlyFactionsIds {
  "FIA"
  "USSR"
  "US"
  "URBAN"
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{60E14907CE56D40D}" : "{06B2CBCEFD52BFBA}Configs/EntityCatalog/RURAL/RURAL_Characters.conf" {
  }
 }
 m_aFlagNames {
 }
}