SCR_FactionHomeTerritoryConfig {
 m_aFactionHomeTerritories {
  SCR_FactionHomeTerritory "{65E8529B5AB4697F}" {
   m_sID "Arleville"
   m_UIInfo SCR_UIInfo "{5AEEE58D0C686C4C}" {
    Name "#AR-MapLocation_Arleville"
   }
   m_iWeight 30
  }
  SCR_FactionHomeTerritory "{65E8529B4714B259}" {
   m_sID "Beauregard"
   m_UIInfo SCR_UIInfo "{5AEEE58D0EDA2268}" {
    Name "#AR-MapLocation_Beauregard"
   }
   m_iWeight 2
  }
 }
 m_bIsFactionPopulation 1
}