SCR_Faction : "{277AE7613D88A55B}Configs/Factions/INDFOR.conf" {
 FactionKey "URBAN"
 FactionColor 0 0.44 0.078 0.25
 UIInfo SCR_FactionUIInfo "{60E14900036D7321}" {
  Name "Urban civilians"
  Icon "{BD2E2F871E6A3EBF}UI/Textures/Flags/Flag_Faction_Base.edds"
  m_sNameUpper "URBAN CIVILIANS"
 }
 "Identity of soldiers" FactionIdentity "{60E149000D2755E0}" : "{320F453E4F0D9CD8}Configs/Identities/FactionIdentity_URBAN.conf" {
 }
 m_OutlineFactionColor 0.001 0.082 0.023 0.25
 m_sFactionFlag "{BD2E2F871E6A3EBF}UI/Textures/Flags/Flag_Faction_Base.edds"
 m_FactionFlagMaterial "{936E6C67A71A9421}Assets/Props/Fabric/Flags/Data/Flag_2_3_White.emat"
 m_FactionLabel FACTION_URBAN
 m_aFriendlyFactionsIds {
  "FIA"
  "USSR"
  "US"
  "RURAL"
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{60E14900036D7338}" : "{F2E0E438A0406286}Configs/EntityCatalog/URBAN/URBAN_Characters.conf" {
  }
 }
 m_aFlagNames {
 }
}