SCR_FactionHomeTerritoryConfig {
 m_aFactionHomeTerritories {
  SCR_FactionHomeTerritory "{65E8529B789D13D9}" {
   m_sID "Arleville"
   m_UIInfo SCR_UIInfo "{65E8529B789D13D6}" {
    Name "#AR-MapLocation_Arleville"
   }
   m_iWeight 4
  }
  SCR_FactionHomeTerritory "{65E8529B789D13D0}" {
   m_sID "Beauregard"
   m_UIInfo SCR_UIInfo "{65E8529B789D13D3}" {
    Name "#AR-MapLocation_Beauregard"
   }
   m_iWeight 40
  }
 }
 m_bIsFactionPopulation 1
}