SCR_Faction : "{7DB5E431F2E16B5F}Configs/Factions/ProtectedFaction.conf" {
 FactionKey "URBAN"
 FactionColor 0 0.44 0.434 0.502
 UIInfo SCR_FactionUIInfo "{60E14900036D7321}" {
  Name "Urban civilians"
  Icon "{C747F852878A3496}Assets/Props/Fabric/Flags/Data/Flag_1_2_White_BCR.edds"
  m_sNameUpper "URBAN CIVILIANS"
 }
 "Identity of soldiers" FactionIdentity "{60E149000D2755E0}" : "{320F453E4F0D9CD8}Configs/Identities/FactionIdentity_URBAN.conf" {
 }
 m_iOrder 11000
 m_OutlineFactionColor 0 0.13 0.128 0.502
 m_NotificationFactionColor 0 0.44 0.433 1
 m_NotificationTextFactionColor 0 0.302 0.297 1
 m_bIsPlayable 0
 m_bShowInWelcomeScreenIfNonPlayable 0
 m_bIsMilitary 0
 m_sFactionFlag "{C747F852878A3496}Assets/Props/Fabric/Flags/Data/Flag_1_2_White_BCR.edds"
 m_FactionFlagMaterial "{936E6C67A71A9421}Assets/Props/Fabric/Flags/Data/Flag_2_3_White.emat"
 m_FactionLabel FACTION_URBAN
 m_CallsignInfo SCR_FactionCallsignInfo "{607A9A9E40D70F6E}" : "{4D4B1F0F0B56B2C9}Configs/Callsigns/Callsigns_Non-Combatant.conf" {
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{60E14900036D7338}" : "{F2E0E438A0406286}Configs/EntityCatalog/URBAN/URBAN_Characters.conf" {
  }
  SCR_EntityCatalog "{60EED3DF4470B77A}" : "{D13190ABA0DD8ECF}Configs/EntityCatalog/URBAN/URBAN_Groups.conf" {
  }
  SCR_EntityCatalogMultiList "{60F11051D72AE1BF}" : "{1941D4DCB14C86D1}Configs/EntityCatalog/URBAN/URBAN_InventoryItems.conf" {
  }
  SCR_EntityCatalogMultiList "{64A5222DB051F14D}" : "{7C53DF3E1349C5B8}Configs/EntityCatalog/CIV/Vehicles_EntityCatalog_CIV.conf" {
  }
  SCR_EntityCatalogMultiList "{64A5222DB67AC002}" : "{361D4401A7A7102A}Configs/EntityCatalog/CIV/WeaponTripod_EntityCatalog_CIV.conf" {
  }
 }
 m_sGroupFlagsImageSet "{301FC1A2A46D3E0D}UI/Textures/GroupManagement/FlagIcons/GroupFlagsIndfor.imageset"
 m_sGroupFlagsImageSetOutlines "{C07D82625600BA21}UI/Textures/GroupManagement/FlagIcons/GroupFlagsIndfor-outline.imageset"
 m_aFlagNames {
  "infantry"
  "amphibious"
  "anti-air"
  "anti-air-artilery"
  "anti-armor-motorized"
  "antiarmor"
  "armored"
  "artillery"
  "combined"
  "helicopter"
  "helicopter-attack"
  "infantry-air"
  "machinegun"
  "maintenance"
  "medical"
  "mortar"
  "motorized"
  "motorized-infantry"
  "recon"
  "recon-motorized"
  "signal"
  "sniper"
  "supply-motorized"
  "undefined"
 }
}