SCR_Faction : "{277AE7613D88A55B}Configs/Factions/INDFOR.conf" {
 FactionKey "URBAN"
 FactionColor 0 0.44 0.434 0.502
 UIInfo SCR_FactionUIInfo "{60E14900036D7321}" {
  Name "Urban civilians"
  Icon "{C747F852878A3496}Assets/Props/Fabric/Flags/Data/Flag_1_2_White_BCR.edds"
  m_sNameUpper "URBAN CIVILIANS"
 }
 "Identity of soldiers" FactionIdentity "{60E149000D2755E0}" : "{320F453E4F0D9CD8}Configs/Identities/FactionIdentity_URBAN.conf" {
 }
 m_OutlineFactionColor 0 0.44 0.434 0.502
 m_bIsPlayable 0
 m_bShowInWelcomeScreenIfNonPlayable 0
 m_bIsMilitary 0
 m_sFactionFlag "{C747F852878A3496}Assets/Props/Fabric/Flags/Data/Flag_1_2_White_BCR.edds"
 m_FactionFlagMaterial "{936E6C67A71A9421}Assets/Props/Fabric/Flags/Data/Flag_2_3_White.emat"
 m_FactionLabel FACTION_URBAN
 m_aFriendlyFactionsIds {
  "FIA"
  "USSR"
  "US"
  "RURAL"
  "GANG"
  "RHS_RF_MSV"
  "RHS_US_USMC"
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{60E14900036D7338}" : "{F2E0E438A0406286}Configs/EntityCatalog/URBAN/URBAN_Characters.conf" {
  }
  SCR_EntityCatalog "{60EED3DF4470B77A}" : "{D13190ABA0DD8ECF}Configs/EntityCatalog/URBAN/URBAN_Groups.conf" {
  }
  SCR_EntityCatalogMultiList "{60F11051D72AE1BF}" : "{1941D4DCB14C86D1}Configs/EntityCatalog/URBAN/URBAN_InventoryItems.conf" {
  }
 }
 m_aFlagNames {
 }
}