SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{60EB3E6261502BCD}" {
   m_sEntityPrefab "{E062ADE88FDC1A41}Prefabs/Characters/Factions/INDFOR/GANG/Character_GANG_Gangsta00.et"
  }
  SCR_EntityCatalogEntry "{60EB579979090927}" {
   m_sEntityPrefab "{1A6501B0C9C50EC4}Prefabs/Characters/Factions/INDFOR/GANG/Character_GANG_Gangsta01.et"
  }
  SCR_EntityCatalogEntry "{60EB5798E93B1F04}" {
   m_sEntityPrefab "{76313550750181EA}Prefabs/Characters/Factions/INDFOR/GANG/Character_GANG_Gangsta02.et"
  }
  SCR_EntityCatalogEntry "{60EEBA8DD972AE52}" {
   m_sEntityPrefab "{93AD79A979E41681}Prefabs/Characters/Factions/INDFOR/GANG/Character_GANG_Gangsta03.et"
  }
 }
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{64DEECE1637D92E1}" {
   m_sIdentifier "Campaign"
   m_aEntities {
    SCR_EntityCatalogEntry "{64DEECE16B3982C7}" {
     m_sEntityPrefab "{D2982D8EDE492D79}Prefabs/Characters/Campaign/Final/Campaign_GANG_Player.et"
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{64DEECE176913D1F}" {
       m_eSlotTypes GROUP_SMALL
      }
     }
    }
   }
  }
 }
}