SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{65BD2C0DDE5D6C75}" {
   m_sEntityPrefab "{58336F8EDDDC54F0}Prefabs/Characters/Factions/INDFOR/GANG/Character_GANG_Randomized.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{65BD2C0DC076AFBA}" {
    }
   }
  }
 }
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{64DEECE1637D92E1}" {
   m_sIdentifier "Campaign"
   m_aEntities {
    SCR_EntityCatalogEntry "{64DEECE16B3982C7}" {
     m_sEntityPrefab "{D2982D8EDE492D79}Prefabs/Characters/Campaign/Final/Campaign_GANG_Player.et"
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{64DEECE176913D1F}" {
       m_eSlotTypes GROUP_SMALL
      }
      SCR_EntityCatalogLoadoutData "{64E1020FE8EF5C4E}" {
       m_fSpawnSupplyCost 20
      }
     }
    }
   }
  }
 }
}