SCR_EntityCatalog {
 m_eEntityCatalogType GROUP
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{60EED3DE87B6FC44}" {
   m_sEntityPrefab "{9EB0377EE756B199}Prefabs/Groups/INDFOR/GANG/Group_GANG_Mix00.et"
  }
 }
}