SCR_EntityCatalog {
 m_eEntityCatalogType GROUP
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{64E120835D41A9E6}" {
   m_sEntityPrefab "{7C5F49C9EE107156}Prefabs/Groups/INDFOR/GANG/Group_GANG_Patrol.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{64E120832BB1847F}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{64E120832F120243}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{60EED3DE87B6FC44}" {
   m_sEntityPrefab "{AFE566DDD3814874}Prefabs/Groups/INDFOR/GANG/Group_GANG_LightFireTeam.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{648B0C57D81CCDE4}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{648B0C57A43E8C58}" {
     m_eSlotTypes 7
    }
   }
  }
 }
}