SCR_EntityCatalogMultiList {
 m_eEntityCatalogType VEHICLE
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{64E1020F892AF8A6}" {
   m_sIdentifier "Vehicles"
   m_aEntities {
    SCR_EntityCatalogEntry "{64E1020B0652F4A1}" {
     m_sEntityPrefab "{A7A9251AA7CA1309}Prefabs/Vehicles/Wheeled/S105/S105_GANG_randomized.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{64E1020B0DCD78D8}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{64E1020B17792A4E}" {
       m_eSlotTypes 56
      }
     }
    }
    SCR_EntityCatalogEntry "{64E1166715FC99BD}" {
     m_sEntityPrefab "{5E901A66815FDAD9}Prefabs/Vehicles/Helicopters/UH1H/UH1H_armed_GANG.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{64E11667E23DCE8A}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{64E11667E57E8D79}" {
       m_eSlotTypes 48
      }
     }
    }
   }
  }
 }
}