SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSetting "{60F0FA299AF8FF6F}" {
   m_Info SCR_UIInfo "{60F0FA267792FC4A}" {
    Name "RURAL"
    Icon "{F29DF4A21175C75D}Assets/Props/Fabric/Flags/Data/Flag_1_2_Everon_BCR.edds"
   }
   m_LabelType FACTION_RURAL
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{60F0FA265607624B}" {
   m_Info SCR_UIInfo "{60F0FA2658E1C7D2}" {
    Name "URBAN"
    Icon "{C747F852878A3496}Assets/Props/Fabric/Flags/Data/Flag_1_2_White_BCR.edds"
   }
   m_LabelType FACTION_URBAN
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{60F0FA26311EB2D5}" {
   m_Info SCR_UIInfo "{60F0FA263A514D6A}" {
    Name "GANG"
    Icon "{CF4545F580A34FA7}Assets/Props/Fabric/Flags/Data/Flag_1_2_Blue_BCR.edds"
   }
   m_LabelType FACTION_GANG
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{6497365B1969144E}" {
   m_Info SCR_UIInfo "{6497365BE4C862C3}" {
    Name "REDPEACE"
    Icon "{2B67EAC609C89A0A}Assets/Props/Fabric/Flags/Data/Flag_1_2_Red_BCR.edds"
   }
   m_LabelType FACTION_REDPEACE
   m_LabelGroupType FACTION
  }
 }
}