SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{658EF9B0E8D8C8B8}" {
   m_Info SCR_UIInfo "{658EF9B0C827D059}" {
    Name "PROTECTED"
    Description "Temporary virtual faction to which belong protected non-combatants and prisoners of war while they are protected by military personal"
    Icon "{C747F852878A3496}Assets/Props/Fabric/Flags/Data/Flag_1_2_White_BCR.edds"
   }
   m_Order 100
   m_LabelType FACTION_PROTECTED
   m_LabelGroupType FACTION
   m_eBlackListedModes 0
  }
  SCR_EditableEntityCoreLabelSetting "{60F0FA299AF8FF6F}" {
   m_Info SCR_UIInfo "{60F0FA267792FC4A}" {
    Name "RURAL"
    Description "Rural civilians tend to live in small villages or isolated houses and are from the same ethnic background as the FIA"
    Icon "{F29DF4A21175C75D}Assets/Props/Fabric/Flags/Data/Flag_1_2_Everon_BCR.edds"
   }
   m_Order 20
   m_LabelType FACTION_RURAL
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{60F0FA265607624B}" {
   m_Info SCR_UIInfo "{60F0FA2658E1C7D2}" {
    Name "URBAN"
    Description "Urban civilians lives in bigger towns and their ethnic background is more diverse"
    Icon "{C39D234EF0D4B94D}Assets/Props/Fabric/Flags/Data/Flag_1_2_N.edds"
   }
   m_Order 21
   m_LabelType FACTION_URBAN
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{60F0FA26311EB2D5}" {
   m_Info SCR_UIInfo "{60F0FA263A514D6A}" {
    Name "GANG"
    Description "Gangs are armed militas from the urban areas, they are to the urban cilians what the FIA are for the rural civilians"
    Icon "{CF4545F580A34FA7}Assets/Props/Fabric/Flags/Data/Flag_1_2_Blue_BCR.edds"
   }
   m_Order 10
   m_LabelType FACTION_GANG
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{6497365B1969144E}" {
   m_Info SCR_UIInfo "{6497365BE4C862C3}" {
    Name "REDPEACE"
    Description "Peacekeeping force from a poor country, armed with soviet-type equipment"
    Icon "{2B67EAC609C89A0A}Assets/Props/Fabric/Flags/Data/Flag_1_2_Red_BCR.edds"
   }
   m_Order 11
   m_LabelType FACTION_REDPEACE
   m_LabelGroupType FACTION
  }
 }
}