SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSetting "{60F0FA299AF8FF6F}" {
   m_Info SCR_UIInfo "{60F0FA267792FC4A}" {
    Name "RURAL"
    Description "Rural civilians tend to live in small villages or isolated houses and are from the same ethnic background as the FIA"
    Icon "{F29DF4A21175C75D}Assets/Props/Fabric/Flags/Data/Flag_1_2_Everon_BCR.edds"
   }
   m_Order 20
   m_LabelType FACTION_RURAL
   m_LabelGroupType FACTION
  }
  SCR_EditableEntityCoreLabelSetting "{60F0FA265607624B}" {
   m_Info SCR_UIInfo "{60F0FA2658E1C7D2}" {
    Name "URBAN"
    Description "Urban civilians lives in bigger towns and their ethnic background is more diverse"
    Icon "{C39D234EF0D4B94D}Assets/Props/Fabric/Flags/Data/Flag_1_2_N.edds"
   }
   m_Order 21
   m_LabelType FACTION_URBAN
   m_LabelGroupType FACTION
  }
 }
}