SCR_MissionHeader {
 World "{5A1415AE6262B722}Worlds/GameMaster/Protection_GM_Arland.ent"
 m_sName "Protection - Game Master Arland"
 m_sAuthor "argeo"
 m_sDescription "Game Master mode with Protection factions"
 m_sLoadingScreen "{EB6A0C33E1FFBAC5}UI/Textures/Common/Protection/Flag_of_the_Red_Crystal.edds"
 m_sPreviewImage "{EB6A0C33E1FFBAC5}UI/Textures/Common/Protection/Flag_of_the_Red_Crystal.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_eEditableGameFlags SpawnAI
 m_bIsSavingEnabled 1
}