SCR_MissionHeader {
 World "{6181D499CE0C1685}Worlds/GameMaster/Protection_GM_Everon.ent"
 m_sName "Protection - Game Master - Everon"
 m_sAuthor "argeo"
 m_sDescription "Game Master mode on Everon, with the Protection factions and features."
 m_sDetails "Build your own scenarios with the towns automatically populated with civilians and the Protection features enabled (additional war crimes, commanding of civilian AIs, capture of enemy AIs)."
 m_sIcon "{93E6EEDBCD12CA2F}UI/Textures/MissionLoadingScreens/GM_Eden.edds"
 m_sLoadingScreen "{93E6EEDBCD12CA2F}UI/Textures/MissionLoadingScreens/GM_Eden.edds"
 m_sPreviewImage "{93E6EEDBCD12CA2F}UI/Textures/MissionLoadingScreens/GM_Eden.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_eEditableGameFlags SpawnAI
 m_eDefaultGameFlags SpawnAI
 m_bIsSavingEnabled 1
}