SCR_MissionHeader {
 World "{5A1415AE6262B722}Worlds/GameMaster/Protection_GM_Arland.ent"
 m_sName "Protection - Game Master - Arland"
 m_sAuthor "argeo"
 m_sDescription "Game Master mode on Arland with the Protection factions and features."
 m_sDetails "Build your own scenarios with the towns automatically populated with civilians and the Protection features enabled (additional war crimes, commanding of civilian AIs, capture of enemy AIs)."
 m_sIcon "{D91B48761E60082F}UI/Textures/Common/Protection/RedCrystal-icon.edds"
 m_sLoadingScreen "{EB6A0C33E1FFBAC5}UI/Textures/Common/Protection/Flag_of_the_Red_Crystal.edds"
 m_sPreviewImage "{EB6A0C33E1FFBAC5}UI/Textures/Common/Protection/Flag_of_the_Red_Crystal.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_eEditableGameFlags SpawnAI
 m_eDefaultGameFlags SpawnAI
 m_bIsSavingEnabled 1
}