SCR_MissionHeader {
 World "{5A1415AE6262B722}Worlds/GameMaster/Protection_GM_Arland.ent"
 m_sName "Protection - Game Master - Arland"
 m_sAuthor "argeo"
 m_sDescription "Game Master mode on Arland, with the Protection factions and features."
 m_sDetails "Build your own scenarios with the towns automatically populated with civilians and the Protection features enabled (additional war crimes, commanding of civilian AIs, capture of enemy AIs)."
 m_sIcon "{94BD54887EAB8288}UI/Textures/MissionLoadingScreens/GM_Arland.edds"
 m_sLoadingScreen "{94BD54887EAB8288}UI/Textures/MissionLoadingScreens/GM_Arland.edds"
 m_sPreviewImage "{94BD54887EAB8288}UI/Textures/MissionLoadingScreens/GM_Arland.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_eEditableGameFlags SpawnAI
 m_eDefaultGameFlags SpawnAI
 m_bIsSavingEnabled 1
}