SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{FF7BB2F4C012B969}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_EmergencyResponseCenter_S_US.et"
  "{1A4947C79F64D9B8}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_EmergencyResponseCenter_S_USSR.et"
 }
}