SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{18BD3B067D00FF3D}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_LivingArea_S_GANG_01.et"
  "{A81F1CA0AAE8561E}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_Antenna_S_GANG_01.et"
  "{7CBCBA91D3F27603}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatSmall/E_VehicleMaintenance_S_GANG_01.et"
  "{E9357026F2325405}PrefabsEditable/Auto/Compositions/Slotted/SlotFlatMedium/E_EmergencyResponseCenter_M_US.et"
  "{B05B1BC6F2EFC4C1}PrefabsEditable/Auto/Compositions/Misc/SubCompositions/Tents/E_EmergencyResponseCenter_S_US.et"
 }
}